# This file was generated by GoReleaser. DO NOT EDIT.
cask "kana" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "4bd6ab0f1a45dce61aad5c1e04afdab8af37a90738f9c532c4f1408ddc91418c"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
    on_arm do
      sha256 "c26800ea222989f76493c9a8656ca4c51f8c19adf9eb93c04e505e1d4814507c"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3bcd96ab899a7191cb31ea557f00c8a8c0684723a7b5c0347f34133f459b3e6"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
    on_arm do
      sha256 "da42eab202fe9ba881bd90d25b37bbe306a14c929d6a26c91eee0e135717fdbd"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
  end

  name "kana"
  desc "Kana CLI"
  homepage "https://github.com/kana-ai/gh-kana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kana"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kana"]
    end
  end

  # No zap stanza required

end
