# This file was generated by GoReleaser. DO NOT EDIT.
cask "kana" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "440842af32d48937cc51133beabb21c743cf3c8fdf19f409479fd2ea5920f1e5"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
    on_arm do
      sha256 "25967222fd8247401b4b78376b98bc1c31e5b6419553227fe590222cb665384b"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
  end

  on_linux do
    on_intel do
      sha256 "08ed96f4ab205e3ba9f3580cb5ff819d7481597314dbfffd43ff93b501003344"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
    on_arm do
      sha256 "e7e964861ed3a3d35859015b845cac70931507cb12101deff85c6f56f83e349e"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
  end

  name "kana"
  desc "Kana CLI"
  homepage "https://github.com/kana-ai/gh-kana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kana"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kana"]
    end
  end

  # No zap stanza required

end
