# This file was generated by GoReleaser. DO NOT EDIT.
cask "kana" do
  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "8ccf33b13fff8eaa3a3701ab92e99bc762e08553b8ed4cb52f57c7f91d0ca208"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
    on_arm do
      sha256 "5db569137026ca70a8851e8680a5e10b09242ae980e3f0de5dfa18e85f7f6f68"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
  end

  on_linux do
    on_intel do
      sha256 "11f9a95f5cb1b368ff0d30fa0163658cc4538a918f52a9142ce5eaf8dcf7d6e9"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
    on_arm do
      sha256 "c9a6cadd3883b8bb187186d8f1eddea01f316bac400843026e6b7b77e8e340df"
      url "https://github.com/kana-ai/gh-kana/releases/download/v#{version}/kana-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kana-ai/gh-kana/"
    end
  end

  name "kana"
  desc "Kana CLI"
  homepage "https://github.com/kana-ai/gh-kana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kana"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kana"]
    end
  end

  # No zap stanza required

end
